{{- if and (not .Values.mongodb.existingConfigMap) (or .Values.mongodb.host .Values.mongodb.db .Values.mongodb.options) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "swimdockerapp.fullname" . }}-mongodb
  labels:
    {{- include "swimdockerapp.labels" . | nindent 4 }}
data:
  {{ .Values.mongodb.hostKey }}: {{ .Values.mongodb.host | quote }}
  {{ .Values.mongodb.dbKey }}: {{ .Values.mongodb.db | quote }}
  {{- if .Values.mongodb.options }}
  {{ .Values.mongodb.optionsKey }}: {{ .Values.mongodb.options | quote }}
  {{- end }}
{{- end }}
